'use client';
import {useMemo,useState} from 'react';

type Salon={id:number;name:string;area:string;rating:number;distance:string;image:string;services:string[];stylists:string[];price:number;next:string};
const salons:Salon[]=[
{id:1,name:'The Groom Room',area:'Koregaon Park, Pune',rating:4.8,distance:'1.2 km',image:'💈',services:['Haircut','Beard Trim','Hair Styling'],stylists:['Aarav','Rohan'],price:299,next:'Today, 7:30 PM'},
{id:2,name:'Urban Trim Studio',area:'Viman Nagar, Pune',rating:4.7,distance:'3.4 km',image:'✂️',services:['Haircut','Beard Trim','Facial'],stylists:['Kabir','Dev'],price:349,next:'Today, 8:00 PM'}
];
export default function Home(){
 const [selected,setSelected]=useState<Salon|null>(null); const [service,setService]=useState('Haircut'); const [stylist,setStylist]=useState(''); const [slot,setSlot]=useState(''); const [booked,setBooked]=useState(false); const [tab,setTab]=useState<'home'|'bookings'|'admin'>('home');
 const slots=useMemo(()=>['7:00 PM','7:30 PM','8:00 PM','8:30 PM','9:00 PM'],[]);
 function confirm(){if(!selected||!stylist||!slot)return;setBooked(true)}
 return <main><header><div className="nav"><div className="brand"><span className="brandmark">t</span>trimzee</div><div className="city">📍 Pune</div><nav><button onClick={()=>setTab('home')}>Discover</button><button onClick={()=>setTab('bookings')}>My bookings</button><button onClick={()=>setTab('admin')}>Admin demo</button></nav><button className="login">Sign in</button></div></header>
 {tab==='admin'?<section className="container"><div className="hero small"><p className="eyebrow">TRIMZEE ADMIN</p><h1>Everything happening in one place.</h1><p>Demo dashboard for salon operations and booking visibility.</p></div><div className="stats"><div><b>24</b><span>Today&apos;s bookings</span></div><div><b>₹8,420</b><span>Today&apos;s revenue</span></div><div><b>92%</b><span>Slot utilization</span></div></div><div className="panel"><h2>Live bookings</h2><p>Rohan · The Groom Room · 7:30 PM · Confirmed</p><p>Kabir · Urban Trim Studio · 8:00 PM · Awaiting payment</p></div></section>:
 tab==='bookings'?<section className="container"><div className="hero small"><p className="eyebrow">MY BOOKINGS</p><h1>Your next look is sorted.</h1><p>Manage upcoming appointments from one place.</p></div>{booked?<div className="booking-card"><div className="check">✓</div><div><h2>Booking confirmed</h2><p>{selected?.name} · {service} · {stylist} · {slot}</p><span>Pay at salon · Pune</span></div><button onClick={()=>setBooked(false)}>Cancel booking</button></div>:<div className="empty">No bookings yet. Pick a salon and book your first appointment.</div>}</section>:
 <><section className="hero container"><div><p className="eyebrow">PUNE&apos;S SMART SALON BOOKING</p><h1>Good hair days,<br/><i>booked instantly.</i></h1><p className="lead">Find a salon, choose your stylist, see the next available slot and book in seconds.</p><div className="search"><span>⌕</span><input placeholder="Search salons or areas in Pune"/><button>Search</button></div><div className="trust"><span>⚡ Real-time slots</span><span>✓ Easy cancellation</span><span>₹ Pay at salon</span></div></div><div className="hero-card"><span>LIVE IN PUNE</span><b>Next available</b><strong>7:30 PM</strong><small>The Groom Room · 1.2 km away</small><button onClick={()=>setSelected(salons[0])}>Book now →</button></div></section><section className="container"><div className="section-head"><div><p className="eyebrow">NEAR YOU</p><h2>Top salons in Pune</h2></div><span>2 demo salons</span></div><div className="grid">{salons.map(s=><article className="salon" key={s.id}><div className="salon-image">{s.image}<span>OPEN</span></div><div className="salon-body"><div className="row"><h3>{s.name}</h3><span className="rating">★ {s.rating}</span></div><p>{s.area} · {s.distance}</p><div className="chips">{s.services.map(x=><span key={x}>{x}</span>)}</div><div className="row bottom"><b>From ₹{s.price}</b><button onClick={()=>{setSelected(s);setBooked(false)}}>View & book</button></div></div></article>)}</div></section></>}
 {selected&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">BOOK APPOINTMENT</p><h2>{selected.name}</h2><p>{selected.area} · ★ {selected.rating}</p><label>Service<select value={service} onChange={e=>setService(e.target.value)}>{selected.services.map(x=><option key={x}>{x}</option>)}</select></label><label>Stylist<select value={stylist} onChange={e=>setStylist(e.target.value)}><option value="">Choose a stylist</option>{selected.stylists.map(x=><option key={x}>{x}</option>)}</select></label><label>Available slots<div className="slotgrid">{slots.map(x=><button className={slot===x?'active':''} key={x} onClick={()=>setSlot(x)}>{x}</button>)}</div></label><div className="payment"><span>Payment</span><b>Pay at salon <small>Online payment can be enabled with Razorpay test mode.</small></b></div><button className="confirm" disabled={!stylist||!slot} onClick={confirm}>Confirm booking · ₹{selected.price}</button></div></div>}
 </main>
}
